### ISSUE TITLE
ngx-quill styles bleed into other components

### ISSUE THREAD

**Issue by allanbond** [KillerCodeMonkey/ngx-quill#1598] opened 2022-09-07 22:20 UTC
Issue: ngx-quill styles bleed into global styles and Angular components that use Shadow DOM.

Description:
For Angular components using ViewEncapsulation.None, the following style behaviors occur for styles defined in that component:

- styles are inserted into the global style namespace
- styles are inserted into the shadow root of components using ViewEncapsulation.ShadowDom

(see the discussion here for more info -> https://github.com/angular/angular/issues/5059)

`<quill-editor>` styles ([here](https://github.com/KillerCodeMonkey/ngx-quill/blob/bd8f2587472088812036dcced6cd6dc76b873103/projects/ngx-quill/src/lib/quill-editor.component.ts#L753-L758)) are inserted into the global style namespace and into the shadow root of Angular components that use ShadowDOM.

This leads to unexpected behavior, particularly in the case of components using `ViewEncapsulation.ShadowDom`.

This StackBlitz [example](https://angular-ivy-5o1knr.stackblitz.io) shows the effect (inspect the DOM to see this in action).
It contains three custom components, each using a different encapsulation strategy. It also includes `<quill-editor>`.

- styles for both 'emulated' and 'none' are inserted in the document style namespace (this is fine)
- styles for both 'emulated' and 'none' encapsulation strategies are inserted into the shadow root (the 'emulated' styles are qualified with the component id and have no negative impact,  whereas the components using no encapsulation override the styles defined in the ShadowDOM component---this is a problem)

This could be avoided if `ngx-quill` uses ViewEncapsulation.Emulated instead of ViewEncapsulation.None.

Has this been tried before? Or are you willing to try this? I'd be willing to submit a PR.

**Comment by KillerCodeMonkey** [comment] 2022-09-08 05:33
the problem is that you should be able to import quilljs css to your css. when you go with emulated css the quilljs css will not apply.

Maybe there is a way, now. But as i created that component long time ago it was the only way to allow to style the component from outside + apply the quilljs css.

**Comment by allanbond** [comment] 2022-09-08 20:06
If quilljs css is imported in application styles.css or in angular.json, it will apply styles even to emulated components.

The change that was made in ngx-quill v14 to display the editor as inline-block is not working, precisely because it does not use emulated encapsulation.

In the attached screenshot, the top example shows ngx-quill w/no encapsulation (current state). The css rule for inline-block style doesn't match anything since it is defined at the top level.

The bottom example shows a version of ngx-quill using emulated encapsulation. As you can see in the devtools screenshot, Angular generates styles specifically targeting the emulated version of ngx-quill, and the inline-block rule is matched and applied.

![image](https://user-images.githubusercontent.com/1049326/189214288-5021c32d-7399-49ad-84c2-028def0ec5e1.png)
![image](https://user-images.githubusercontent.com/1049326/189215317-2a052f4a-f7d7-4cc3-91cc-08f2291e14a8.png)

**Comment by KillerCodeMonkey** [comment] 2022-09-08 20:14
And are you able to override the inline-block styling if you want?

If so feel free to create a PR switching the view encapsulation.

I do not even remember why this default styling was added.

allanbond ***@***.***> schrieb am Do., 8. Sept. 2022, 22:07:

**Comment by KillerCodeMonkey** [comment] 2022-09-13 05:35
any updates on that?

**Comment by allanbond** [comment] 2022-09-13 14:09
Yes you can override the inline-block styling if you want. I checked the commit history and found a note that inline-block was applied so that the component behaves more like standard html controls.

I opened a PR to change the encapsulation strategy to Emulated.

**Comment by KillerCodeMonkey** [comment] 2022-09-14 05:54
released in v19. i decided to go for a major version bump. for safety purposes.

**Closed by KillerCodeMonkey** 2022-09-14 05:54 UTC
