### ISSUE TITLE
Blur event is not triggered when we click on the checkbox after we focus in ngx-quill 

### ISSUE THREAD

**Issue by pavitsrivatsan** [KillerCodeMonkey/ngx-quill#1683] opened 2023-04-28 17:05 UTC
The blur event doesn't get triggered when we check on a check box outside the editor. 

Minimal reproduction : 
https://ngx-quill-angular-lxt4zn.stackblitz.io/

**Comment by ginobean** [comment] 2023-09-20 10:10
It looks to me like I can add a blur event listener directly to the scrollingContainer field of the QuillEditor:

```
onQuillEditorCreated(editorInstance: any) {
  editorInstance.scrollingContainer.addEventListener(
    'blur',
    (event: FocusEvent) => this.quillEditorBlur(event)
  );
}

quillEditorBlur(e: FocusEvent) {
  console.log('mark corresponding control has having been touched..');
}

```
Can you simply update the blur handling of the QuillEditor so that it does what my code above does? 

Took a brief look at your blur handling code, in quill-editor.component.mjs, and it currently seems to be more complicated than it needs to be, without providing the basically functionality that we were expecting it to have.

**Comment by KillerCodeMonkey** [comment] 2023-09-20 15:01
it depends if the quill editor is really losing the focus when this is happens.
Only because blur is called for the scrollingContainer does not mean quilljs lost the focus (you are not able to type anymore).

there are many open issues regarding this in react-quill, quilljs repo.

**Comment by ginobean** [comment] 2023-09-20 19:48
The problem is that if I click inside the quill editor, then click on a different control, in the same form, your blur event is NOT getting called. In contrast, the blur event code example that I provided DOES get called. This is critical, if you need to know if a control has been touched at all, using blur events. 

When I tried to use your blur event handling, to determine if the quill editor had been touched, was unable to do so reliably. Whereas, my code does seem to reliably handle it.

**Comment by KillerCodeMonkey** [comment] 2023-09-21 05:09
Yep but only for controls to being touched. But as I said not 100%
reliable. Because you Event gets triggered when quilljs is not "blurred" in
the meaning that you lost the focus an can not type in the editor.

If I implement you solution I will get many issues about "blur gets
triggered even the editor does not lose focus".

Since I want to stay as much as possible at the native quilljs behavior I
decided to go that way.

But maybe I could implement both and let decide the developer which
behavior first more their needs.

Gino ***@***.***> schrieb am Mi., 20. Sept. 2023, 21:48:

**Comment by ginobean** [comment] 2023-09-21 11:51
Implementing both sounds like reasonable approach. I generally prefer to use the API, and not delve into the guts, unless absolutely necessary!

**Comment by KillerCodeMonkey** [comment] 2023-09-21 12:44
@ginobean i release 22.1.0-beta.2 i decided to go with 2 additional outputs (onNativeFocus, onNativeBlur). I added an additional fix that the native "blur" is not triggered when clicking something in the toolbar.

Could you try it if it fits your needs? Thanks

**Comment by ginobean** [comment] 2023-09-22 10:41
Yes. release 22.1.0-beta.2 resolves the blur issue, for me, via the onNativeBlur. 

BTW, I don't know if this is due to a quirk of my local build environment or not, but I noticed that when I tried to build your v22.1.0-beta.2 ngx-quill locally, using 'npm run build', I encountered a couple typescript errors, 

```
Compiling with Angular sources in Ivy full compilation mode.
projects/ngx-quill/src/lib/quill-editor.component.ts:141:29 - error TS2769: No overload matches this call.
  Overload 1 of 4, '(token: ProviderToken<unknown>): unknown', gave the following error.
    Argument of type 'InjectionToken<Document>' is not assignable to parameter of type 'ProviderToken<unknown>'.
      Type 'InjectionToken<Document>' is not assignable to type 'InjectionToken<unknown>'.
        Property '_desc' is protected but type 'InjectionToken<T>' is not a class derived from 'InjectionToken<T>'.
  Overload 2 of 4, '(token: ProviderToken<unknown>, flags?: InjectFlags): unknown', gave the following error.
    Argument of type 'InjectionToken<Document>' is not assignable to parameter of type 'ProviderToken<unknown>'.

141   private document = inject(DOCUMENT)
                                ~~~~~~~~

projects/ngx-quill/src/lib/quill-editor.component.ts:267:90 - error TS2339: Property 'body' does not exist on type 'unknown'.

267         bounds = this.service.config.bounds ? this.service.config.bounds : this.document.body
                                                                                             ~~~~

```
I resolved both typescript errors, by adding `// @ts-ignore` above each of the two errors, and that allowed the build to succeed.

**Comment by KillerCodeMonkey** [comment] 2023-09-22 10:47
maybe you have different tsconfig settings?

But i will release the beta version as a final release and will close this issue :) 

Thanks

**Closed by KillerCodeMonkey** 2023-09-22 10:47 UTC

**Comment by ginobean** [comment] 2023-09-22 10:49
Sounds good. Thanks for the update! :).

**Comment by skovalyov** [comment] 2024-02-13 10:42
@KillerCodeMonkey But when the component is used in a reactive form and `{ updateOn: 'blur' }` is used for its form control, then it still relies on `onBlur()` not on `onNativeBlur()`. Would it make sense to make it configurable using, for example, some component property instead of two event handlers?

**Comment by KillerCodeMonkey** [comment] 2024-02-13 10:53
In General I would like to keep the output, because maybe in some cases it make sense to keep track of both.

But I am up to improvements. Can I Do something to make your Integration easier?

**Comment by skovalyov** [comment] 2024-02-13 12:30
@KillerCodeMonkey Let me explain my use case.

I have a reactive form with an ngx-quill editor as one of the controls. In controller it is declared as:

```ts
noteForm = this.fb.group({
  noteContent: this.fb.control<string>(null, { updateOn: 'blur' })
});
```

And in template it is declared as:

```html
<quill-editor
  formControlName="noteContent"
  [modules]="quillModules">
</quill-editor>
```

When I subscribe to `valueChanges`, it does not emit when I click on another control outside the quill editor instance.

```ts
this.noteForm.get("noteContent").valueChanges.subscribe((value) => {
  /* Do something */
});
```

The underlying reason, as I understand, is the same as discussed in this issue, i.e. blur is not emitted.

What I have to do with the current API is to add `onNativeBlur` event handler and patch the reactive form manually, which is obviously not a good way to work with reactive forms. 

What I think of is to have some property, e.g. `blurEventHandler: 'quill' | 'native'` that will determine what blur event should be used to notify the reactive form, if it is possible. Or some alternative solution?
