### ISSUE TITLE
control always dirty

### ISSUE THREAD

**Issue by matrium0** [KillerCodeMonkey/ngx-quill#121] opened 2018-02-27 13:15 UTC
For some reason it seems like the control is always marked as dirty in my project, even when the user just loaded the page and changed nothing in the quill editor

I use the component like this:
<quill-editor [(ngModel)]="offer.customerComment" id="customerComment" name="customerComment" [modules]="{toolbar:[['bold', 'italic', 'underline'],['link']]}"
                                  [formats]="['bold','italic','underline','link']" class="form-control additionalConditions" placeholder="write your comment here"></quill-editor>

I also tried on an almost blank page with no logic, same behavior: in the NgForm the field controls.customerComment.dirty always seems to be true

**Comment by KillerCodeMonkey** [comment] 2018-02-27 13:16
Could you try it with react forms? And the formControl input?

**Comment by matrium0** [comment] 2018-02-27 13:45
Wow, thats what I call fast answer, thanks!

I am not familiar with reactive forms right now, just the template based approach, sorry! The input was "<p>test</p>" in this case.

(I tested with v2.0.4 and 2.1.1).

**Comment by KillerCodeMonkey** [comment] 2018-02-27 13:46
Yeah, I think there are some quirks with template driven forms.

Just checkout my example repo —> there is also on editor with formControl ;)

**Comment by KillerCodeMonkey** [comment] 2018-03-04 20:24
did you solved it?

**Comment by matrium0** [comment] 2018-03-12 07:03
No, not really, but I found a workaround, which is a directive that marks
the control as "pristine" after every input. Of course that has limitations
too, but in my case I can live with that, since the editor is part of a big
form and it is highly unlikely that it will be the only field that changes
- so it's not a big deal that this one input-control is never dirty now.

Thanks for your answers!

2018-03-04 21:24 GMT+01:00 Bengt Weiße <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment] 2018-04-30 14:09
Please Check for reactive forms when You Set You Initial value. In You Set
IT After the Editors initialising, IT is Marked as dirty ;), because it is
something like a control change

Chandraprakash Sharma <notifications@github.com> schrieb am Mo., 30. Apr.
2018, 15:18:

**Comment by mecp** [comment] 2018-04-30 14:32
@KillerCodeMonkey yeah, actually that's when it is set as dirty. So with other form controls when I use `formGroup.reset(initialValue)`, they are not marked as dirty. I specifically use `reset()` instead of `patchValue()` or `setValue()` to not have controls as dirty.

I found some relevant discussion here https://github.com/kekeh/mydatepicker/issues/295 and https://github.com/angular/angular/issues/11073.

Right now, I am using a workaround to explicitly set quill-editor form controls as pristine immeidately after resetting.

**Comment by KillerCodeMonkey** [comment] 2018-07-06 09:37
@mecp could you check if this problem exists in latest version 3.3.0?

**Comment by jberall** [comment] 2018-07-09 15:15
I am using reactive forms and have the same issue.
Angular 6.
The value is not updating on change.  It seems to only be updating when you click another field.
So it is not only the pristine that is the issue.

**Comment by KillerCodeMonkey** [comment] 2018-07-09 15:30
Could You build a plunkr to visualize Your issue? Or can You reproduce the
issue with the Demo Repo? There the formcontrol Updates like it should

jberall <notifications@github.com> schrieb am Mo., 9. Juli 2018, 17:15:

**Comment by jberall** [comment] 2018-07-09 16:16
I made a stackblitz and their is no issue.
The only difference is in the Material, cdk and animations.

I don't have time to investigate now but will try and understand why?
Weird.
Thanks for the prompt reply!
https://stackblitz.com/github/jberall/steve-toolbar

**Comment by kamilchlebek** [comment] 2018-10-25 11:19
In my case control is always dirty because of initial `text-change` event (https://github.com/KillerCodeMonkey/ngx-quill/blob/develop/src/quill-editor.component.ts#L256).

When I populate text editor with content from db (previously we were using different editor), on initial cycle quill will change HTML a bit causing `text-change` event to be fired. 

Would be great if we could conditionally disable initial `text-change` event callback. Maybe it isn't needed at all in the beginning and event listener should be added after init.

**Comment by KillerCodeMonkey** [comment] 2018-10-25 11:57
yeah but how do i know it is the inital content change?

I only know the value of the model, with that value i initialise the edito as initial content.
So you could simply init the editor if you have the really initial value of your model.

like --> do not render the editor until you have the initial value.
How do i know the if the change is the inital change after the editor is already there.

It could be that you model is not set at the beginning, because it is really not set at all. So the first change need to mark the model as dirty ;).
So if you want to render the editor, before you have the value from your db/API whatever you could reset the models state on your own.

**Comment by KillerCodeMonkey** [comment] 2018-12-03 13:30
Thats the spirit!

i thought about it :).

I have the plan to look into this in in the near future.
Feel free to add you to the "contributers" section in the package.json ;)

Let me know if you need help or you have no time, so you can share some code and i finalize it.

Thanks!

**Comment by KillerCodeMonkey** [comment] 2018-12-03 21:38
@earshinov maybe you can validate that this issue is fixed and close the issue? thanks :)

**Comment by earshinov** [comment] 2018-12-04 21:33
@KillerCodeMonkey , sorry for disappearing, did not manage to find time today. Will do it asap tomorrow.

**Comment by KillerCodeMonkey** [comment] 2018-12-05 06:48
@earshinov no probs :). 

i forked your stackblitz and it is working with the latest release:
https://ngx-quill-dirtiness-demo-ephxwx.stackblitz.io/

**Closed by KillerCodeMonkey** 2018-12-05 06:48 UTC
Labels: help wanted

**Comment by tarmo-randma** [comment] 2020-04-11 12:30
Care to post a link to the stackblitz so that we could also see the code? I do not know how to reverse trace the demo page to an editor.
