### ISSUE TITLE
Text length validation out of sync with actual text length

### ISSUE THREAD

**Issue by maciej-sielski** [KillerCodeMonkey/ngx-quill#815] opened 2020-03-20 14:56 UTC
Hi,
I'm not sure if this is the issue with ngx-quill or just quill, but I kindly ask for your help.

I defined a handler to `onContentChanged` event so it can give me a total text length

`public handler (e: ContentChange) { this.textLength = +e.text.length; }`

This handler is invoked when I enter / remove text, but in following cases it is not:
- select whole text and delete (should be invoked with empty text)
- add a whitespace character at the beginning or end of whole text

Additionally when I clear the text and I have minLength set to 100, then form control is in invalid state saying that I currently have 38 characters (should say that I have 0). In my case initial value had 38 characters, so maybe there's something wrong with quill native events being handled.

I'm using
"ngx-quill": "8.0.0",
"quill": "1.3.7",

**Comment by KillerCodeMonkey** [comment] 2020-03-20 15:11
a demo repo or codepen/stackblitz would be nice :).

I can not reproduce this issue. If i clear my editor the length is 1, because quilljs content is at least a `\n`.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2264672/77177209-6d1dea00-6ac5-11ea-9797-c88f2f7df17d.gif)

**Comment by maciej-sielski** [comment] 2020-03-20 16:38
Naturally. [https://angular-uv4fmk.stackblitz.io](https://angular-uv4fmk.stackblitz.io)

onContentChanged is working on stackblitz, so I guess I messed something up. Please check validation in the following case:

* we start with an empty form
* we update it with a value from somewhere else (e.g. ngrx or whatever)
* now validation shows no errors, even though it should (value is too short)
* now let's add spaces at the end - this will trigger onContentChanged with correct value (so no issue here), but validation error still says that "given" has not changed. The same is reproducible when you add spaces at the beginning. Validation trims the text and then checks its length.

Do you want me to change the issue title?

**Comment by KillerCodeMonkey** [comment] 2020-03-20 17:09
Change IT. And maybe IT is more a Feature request. So you can add another
Input property If min and max validation should trim trailing whitespaces

maciej-sielski <notifications@github.com> schrieb am Fr., 20. März 2020,
17:39:

**Comment by maciej-sielski** [comment] 2020-03-20 17:56
I agree that switch for validation (trim or not) is a change request. However consistency, in my opinion, is not.
I've updated stackblitz. Text emitted by onContentChanged contains trailing spaces, where validator omits them (even though form control value also contains them).

**Comment by KillerCodeMonkey** [comment] 2020-03-21 08:59
should be fixed with 8.1.0

https://github.com/KillerCodeMonkey/ngx-quill/releases/tag/8.1.0

**Closed by KillerCodeMonkey** 2020-03-21 08:59 UTC
