### ISSUE TITLE
Randomly creates ghost lines when using IME input.

### ISSUE THREAD

**Issue by linjie0928** [KillerCodeMonkey/ngx-quill#1821] opened 2024-03-21 09:43 UTC
When I input Chinese IME, the program randomly creates line breaks, and the generated blank lines cannot be deleted.
This only happens when used inside Angular, and it will not happen when imported directly into HTML.

in action video:
https://github.com/KillerCodeMonkey/ngx-quill/assets/44791594/d51f16ae-4ec4-4f0e-9d2b-d85125975182

**Comment by linjie0928** [comment] 2024-03-21 09:57
好的，以下是翻譯：

I found the exact sequence to trigger it.
1. Entering a letter into an IME
2. Delete key 
3. Enter key
ghost line will apear.

https://github.com/KillerCodeMonkey/ngx-quill/assets/44791594/5aaf7c9f-dcf1-4d59-ba44-49afa272ab36

**Comment by KillerCodeMonkey** [comment] 2024-03-21 09:59
can you please check this if this appears in native quilljs editor as well?

because i am not doing special. it should be a quilljs issue.
Please check quill v1 and v2 release candidate.

**Comment by linjie0928** [comment] 2024-03-21 10:03
This problem does not occur in native quilljs, but it does happen if I directly import quill.js into Angular without using ngx-quill.

**Comment by KillerCodeMonkey** [comment] 2024-03-21 10:17
but then there is nothing i can do. because i have no special handling in there that could produce this.

**Comment by linjie0928** [comment] 2024-03-21 10:20
^2.0.0-rc.3

**Comment by linjie0928** [comment] 2024-03-21 10:21
In your example, you can reproduce the same situation:
https://killercodemonkey.github.io/ngx-quill-example/

My version is ^2.0.0-rc.3

**Comment by KillerCodeMonkey** [comment] 2024-03-21 10:24
strange. but i have no glue why this should happen.
i just go with the quilljs api to insert content and do not touch the real content/user input. just connecting it with angular inputs/outputs.

so if you have an idea. let me know

**Comment by luin** [comment] 2024-03-22 03:18
I didn't reproduce it actually: https://share.slab.com/1y3BXNSs

Also not sure why in your screencast, the placeholder presented when the caret is at the second line: https://share.slab.com/8hP0ZlY2.

**Comment by linjie0928** [comment] 2024-03-22 03:31
The strange caret position is the ghost line i talking about. XD
Maybe it’s because Taiwan’s phonetic IME is rather special....
I will encounter the same situation on safari.
Or it's a OS problem.

**Comment by linjie0928** [comment] 2024-03-25 04:21
I have been looking for the problem for a long time. The difference I have found so far is that if I run Quill directly in index.html, there is no problem. But once I move it to the component and leave the IME, the ghost line will appear.

<img width="1018" alt="截圖 2024-03-25 中午12 15 35" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/44791594/86005494-645d-4c6d-b129-983d67785e52">

**Comment by KillerCodeMonkey** [comment] 2024-03-25 10:06
since then it is a general problem angular + quill + ime and is not related to this package here.

It would be nice that this issue moves then somewhere it really belongs to :D

**Comment by linjie0928** [comment] 2024-03-25 11:03
I'm wondering how best to address this issue that's been significantly hindering the development of my project. I've attempted to raise it on the quill.js side, but it's been closed by @luin without much follow-up. Would it be appropriate to escalate this matter to the Angular team?"

**Comment by linjie0928** [comment] 2024-03-26 03:48
I've identified the issue; we need to exclude compositionend from zone.js within the polyfill.
@KillerCodeMonkey 

<img width="849" alt="截圖 2024-03-26 上午11 42 46" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/44791594/24d31993-d611-43ca-8f44-53bdb059fd91">

**Comment by KillerCodeMonkey** [comment] 2024-03-26 05:55
But Do you know What other Effects That will have.

Because changing default angular/zone.js behavior is maybe not the Best idea.

Maybe it is working now with your issue but Produces some more for others

**Comment by KillerCodeMonkey** [comment] 2024-03-26 06:14
So i will add section for known issues and add there some hints about deactivating zonejs event on own risk.

**Comment by KillerCodeMonkey** [comment] 2024-03-26 06:23
I added the section https://github.com/KillerCodeMonkey/ngx-quill?tab=readme-ov-file#known-issues

**Comment by KillerCodeMonkey** [comment] 2024-03-26 14:31
I will close this because i will not globally unpatch events to avoid unexpected sideeffects in other apps

**Closed by KillerCodeMonkey** 2024-03-26 14:31 UTC

**Comment by MurmursDev** [comment] 2025-04-07 06:20
You can try zoneless https://angular.dev/guide/experimental/zoneless. It works but is still in experimental

**Comment by KillerCodeMonkey** [comment] 2025-04-07 06:24
yep. i have an eye on this feature.
