### ISSUE TITLE
ERROR in Can't bind to 'content' since it isn't a known property of 'quill-view-html'.

### ISSUE THREAD

**Issue by EduardRotaru** [KillerCodeMonkey/ngx-quill#1141] opened 2021-01-19 13:18 UTC
I am trying to build the project for production but I get this error:

`ERROR in Can't bind to 'content' since it isn't a known property of 'quill-view-html'.
1. If 'quill-view-html' is an Angular component and it has 'content' input, then verify that it is part of this module.
2. If 'quill-view-html' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        {{titleForm}}
      </div>
      <quill-view-html [ERROR ->][content]="contentForm" class="blog_post_form_title_content"></quill-view-html>

      <p *ngIf="cr")
'quill-view-html' is not a known element:
1. If 'quill-view-html' is an Angular component, then verify that it is part of this module.
2. If 'quill-view-html' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        {{titleForm}}
      </div>
      [ERROR ->]<quill-view-html [content]="contentForm" class="blog_post_form_title_content"></quill-view-html>

 ")`

It works fine on localhost, it just can't build on production mode.

I am using
"ngx-quill": "^5.2.0",
Angular CLI: 8.3.29
Node: 12.18.0
OS: win32 x64
Angular: 8.2.14

This is the configuration:

`   imports: [

    CommonModule,
    FormsModule,
    ReactiveFormsModule,

    HighlightJsModule,

    MatFormFieldModule,
    MatAutocompleteModule,
    MatIconModule,
    MatChipsModule,
    MatFormFieldModule,
    MatInputModule,

    QuillModule.forRoot({
      modules: {
        syntax: true,
        toolbar: [
          ['bold', 'italic', 'underline', 'strike'], // toggled buttons
          ['blockquote', 'code-block'], // Code Block
          [{ 'header': 1 }, { 'header': 2 }], // custom button values
          [{ 'list': 'ordered' }, { 'list': 'bullet' }],
          [{ 'script': 'sub' }, { 'script': 'super' }], // superscript/subscript
          [{ 'indent': '-1' }, { 'indent': '+1' }], // outdent/indent
          [{ 'direction': 'rtl' }], // text direction
          [{ 'size': ['small', false, 'large', 'huge'] }], // custom dropdown
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
          [{ 'color': [] }, { 'background': [] }], // dropdown with defaults from theme
          [{ 'font': [] }],
          [{ 'align': [] }],
          ['clean'], // remove formatting button
          ['link', 'image'], // link and image, video
        ]
      }
    }),
    BlogPostsFormRoutingModule,

  ],`

The usage:
`      <quill-view-html [content]="contentForm" class="blog_post_form_title_content"></quill-view-html>`

I mean it works just fine on local.
One more note is that.. The configuration is a child module of another child that goes in the AppModule. Should I check the order of imports? I mean everything works fine on local, I don't think that is a problem.

Thank you

**Comment by KillerCodeMonkey** [comment] 2021-01-19 13:24
could you please try to add QuillModule to the imports of your child module but without the `forRoot` call?

**Comment by EduardRotaru** [comment] 2021-01-19 13:32
Yes, it still shows the same, I did build without --prod and it builds

**Comment by KillerCodeMonkey** [comment] 2021-01-19 14:02
nice with your angular upgrade. i do not officially support angular 8.

and you should use @types/quill: "^1.x"

I extended my demo repo, with a usage of the html-view component in a child module:
https://killercodemonkey.github.io/ngx-quill-example/

Scroll down to something with "ChildModule"

**Comment by KillerCodeMonkey** [comment] 2021-01-19 15:44
i close it since it is working in my demo. Feel free to reopen it after you are using a supported version + maybe stackblitz to reproduce the issue

**Closed by KillerCodeMonkey** 2021-01-19 15:44 UTC

**Comment by EduardRotaru** [comment] 2021-01-19 19:30
Thank you for help, updating solved the issue, even tho I have some new issues because of the new version, but those I can fix them easily.
