### ISSUE TITLE
patchValue and  http subscribe not setting value  

### ISSUE THREAD

**Issue by coderrepo** [KillerCodeMonkey/ngx-quill#98] opened 2018-01-13 07:56 UTC
I have following code to set HTML text from the database. 

HTML string stored like this in the databse 
<ol><li>one</li><li>Two</li><li>Three</li></ol>

when I set the content inside HTTP subscribe.
`    this._jobService.readJob(this.jobId).subscribe(res => {
       this.fetchJob = res.json();
      
      this.jobInfoFormGroup.controls['description'].patchValue(this.fetchJob.description); 
    });`

in the view
	<quill-editor formControlName="description" [style]="{height: '250px'}" [modules]="{toolbar: [ [{ 'header': 1 }, { 'header': 2 }], ['bold', 'italic', 'underline'],[{ 'list': 'ordered'}, { 'list': 'bullet' }]]}">
										</quill-editor>

HTML string display as a pragraph. 
<p>OneTwoThree</p>

Any workaround for this?

**Comment by KillerCodeMonkey** [comment] 2018-01-13 08:29
Maybe you can share some code?

Am 13.01.2018 8:56 vorm. schrieb "coderrepo" <notifications@github.com>:

**Comment by coderrepo** [comment] 2018-01-13 12:39
Form initalization code

`  builtForm(): void {
    this.jobInfoFormGroup = this._fb.group({
      description: [''],
    }
    );`

Please note this is angular universal server-side rendering apps.

**Comment by KillerCodeMonkey** [comment] 2018-01-13 12:40
I thought quilljs is not working with angular universal because it is using
the document object to create the editor instance Oo.

You should get a compilation error.

Am 13.01.2018 1:39 nachm. schrieb "coderrepo" <notifications@github.com>:

**Comment by coderrepo** [comment] 2018-01-13 12:49
it is working nicely when I set HTML content via the button click. 
 
Like this 
`  patchValue() {
    this.jobInfoFormGroup.controls['description'].patchValue(/<ol><li>One</li><li>Two </li><li>Three</li></ol>`);
  }`

**Comment by KillerCodeMonkey** [comment] 2018-01-13 12:51
I thought the Problem is that it is not working with patch value?

Is it possible for you to Providence an example wäre you combine
initialising the control, editor and your http + patch value Problem?



Am 13.01.2018 13:49 schrieb "coderrepo" <notifications@github.com>:

**Comment by coderrepo** [comment] 2018-01-13 13:00
I am getting an error when building the application for production.

**document is not defined**

**Comment by coderrepo** [comment] 2018-01-13 13:01
but it works well in the development environment.

**Comment by KillerCodeMonkey** [comment] 2018-01-13 13:24
Yeah that is what i ment. Quill is using document which will not work with
angular universal.

Just ask at the quilljs repo ;)

Am 13.01.2018 14:01 schrieb "coderrepo" <notifications@github.com>:

**Comment by coderrepo** [comment] 2018-01-13 14:55
https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/client/app/shared/quill-editor/quill-editor.component.ts

I implemented using above code. It works well. this may help others.

**Comment by KillerCodeMonkey** [comment] 2018-01-16 09:40
so you solved your problem?

**Comment by KillerCodeMonkey** [comment] 2018-01-19 09:25
any update? If anything is working for you, please close the issue

**Closed** 2018-01-22 07:28 UTC
