### ISSUE TITLE
How to set quill-editor modules from a external file?

### ISSUE THREAD

**Issue by pedrollmatias** [KillerCodeMonkey/ngx-quill#206] opened 2018-07-05 18:58 UTC
I'm using angular 6 and the last ngx-quill version. I want to set my quill-editor modules imported from another file. The problem is that I need the event emitted by (onEditorCreate) to instantiate this modules, but I'm getting the error: 
`ERROR TypeError: Cannot read property 'modules' of undefined`

This is my code:
**app.component.ts:**

```
import { Component, OnInit } from '@angular/core';
import { QuillEditorComponent } from 'ngx-quill/src/quill-editor.component';
import CardQuill from './card-quill'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.component.css']
})
export class AppComponent implements OnInit {
  quill: any;

  constructor() {  }

  ngOnInit() {}

  setEditor(editor) {
    this.quill = new CardQuill(editor);
  }
}
```

The template file:
**app.component.html**
`<quill-editor (onEditorCreated)="setEditor($event)" [modules]="quill.modules"></quill-editor>`

and finally my card-quill.ts, which I want to export the modules:
**card-quill.ts**
```
export default class CardQuill {

  editorInstance: any;
  modules = {
     toolbar: {
        container:  [
          ['bold', 'italic', 'underline', 'strike', 'code'],
          [{ 'color': [] }],  
        ]
      }
  }

  constructor(editorInstance: any) {
     this.editorInstance = editorInstance;
  }
}
```

If I put all the card-quill file inside the app.component.ts, it works fine. I think what is happening here is that in the template, [modules] = "quill.modules" is trying to make the bind before the editor has been instantiated. 

I don't know if I'm doing this on the correct way, but I don't know how to bind the modules from a external file. Can anyone help me?

**Comment by KillerCodeMonkey** [comment] 2018-07-05 19:07
I Do Not Know why You Do You have an external Class for this and why it
needs to Know the quill Module. Simple Export the static List of modules,
import it and Pass it to the quilleditor component.

pedrollmatias <notifications@github.com> schrieb am Do., 5. Juli 2018,
20:58:

**Comment by pedrollmatias** [comment] 2018-07-05 19:14
Thanks for the fast answer. There are two problems here: First, I need to use the same module structure in different components. Second, I have some handlers in my real file. So, in each component I have to repeat this code and I hope it isn't the right way.

This is my real card-quill.ts:
```
import * as QuillNameSpace from 'quill';
let Quill: any = QuillNameSpace;
let fontSizeStyle = Quill.import('attributors/style/size');
fontSizeStyle.whitelist = ['14px', '16px', '20px', '24px', '28px', '32px', '36px', '40px', '44px' ,'48px', '60px', '72px'];
Quill.register(fontSizeStyle, true);

export default class CardQuill {

  sizes: string[] = ['14px', '16px', '20px', '24px', '28px', '32px', '36px', '40px', '44px' ,'48px', '60px', '72px'];
  sizeIndex: number = this.normalSizeIndex();
  editorInstance: any;
  modules = {
    toolbar: {
      container:  [
        ['bold', 'italic', 'underline', 'strike', 'code'],
        ['text-left', 'text-center', 'text-right', 'text-justify'],
        ['font-increase', 'font-decrease'],
        [{ 'color': [] }],  
      ],
      handlers: {
        'text-left': () => { this.textAlignment(null) },
        'text-center': () => { this.textAlignment('center') },
        'text-right': () => { this.textAlignment('right') },
        'text-justify': () => { this.textAlignment('justify') },
        'font-increase': () => { this.fontSize('increase') },
        'font-decrease': () => { this.fontSize('decrease') }
      }
    }
  };

  constructor(editorInstance: any) {
    this.editorInstance = editorInstance;
  }

  normalSizeIndex(): number{
    return this.sizes.indexOf('24px');
  }

  textAlignment(position: string): void {
    this.editorInstance.format('align', position);
  }

  fontSize(action: string): void {
    if(action == 'decrease' && this.sizeIndex > 0)
      this.sizeIndex--;
    if(action == 'increase' && this.sizeIndex < (this.sizes.length - 1))
      this.sizeIndex++;
    this.editorInstance.format('size', this.sizes[this.sizeIndex]);
  }
}
```

**Comment by pedrollmatias** [comment] 2018-07-05 19:33
Humm, good catch! I think the second option (file without Class) is better because its easier to do the two-way data binding (I need this functionality in each component). Am I right?

**Comment by KillerCodeMonkey** [comment] 2018-07-05 20:29
Yep simply import Your ts File Listen to the oneditorcreated event to Get
the quill instance and Call Your helper functions of needed.

pedrollmatias <notifications@github.com> schrieb am Do., 5. Juli 2018,
21:33:

**Comment by pedrollmatias** [comment] 2018-07-05 20:35
Did it! This is exactly what I was looking for. I chose to solve by inheritance and here is the final result:

**card-quill.component.ts**
```
import { Component } from '@angular/core';
import * as QuillNameSpace from 'quill';
let Quill: any = QuillNameSpace;
let fontSizeStyle = Quill.import('attributors/style/size');
fontSizeStyle.whitelist = ['14px', '16px', '20px', '24px', '28px', '32px', '36px', '40px', '44px' ,'48px', '60px', '72px'];
Quill.register(fontSizeStyle, true);

@Component({
  selector: 'app-card-quill',
  templateUrl: './card-quill.component.html',
  styleUrls: ['./card-quill.component.css']
})

export class CardQuillComponent {

  sizes: string[] = ['14px', '16px', '20px', '24px', '28px', '32px', '36px', '40px', '44px' ,'48px', '60px', '72px'];
  sizeIndex: number = this.normalSizeIndex();
  editorInstance: any;
  modules = {
    toolbar: {
      container:  [
        ['bold', 'italic', 'underline', 'strike', 'code'],
        ['text-left', 'text-center', 'text-right', 'text-justify'],
        ['font-increase', 'font-decrease'],
        [{ 'color': [] }],  
      ],
      handlers: {
        'text-left': () => { this.textAlignment(null) },
        'text-center': () => { this.textAlignment('center') },
        'text-right': () => { this.textAlignment('right') },
        'text-justify': () => { this.textAlignment('justify') },
        'font-increase': () => { this.fontSize('increase') },
        'font-decrease': () => { this.fontSize('decrease') }
      }
    }
  };

  constructor() {}

  normalSizeIndex(): number{
    return this.sizes.indexOf('24px');
  }

  textAlignment(position: string): void {
    this.editorInstance.format('align', position);
  }

  fontSize(action: string): void {
    if(action == 'decrease' && this.sizeIndex > 0)
      this.sizeIndex--;
    if(action == 'increase' && this.sizeIndex < (this.sizes.length - 1))
      this.sizeIndex++;
    this.editorInstance.format('size', this.sizes[this.sizeIndex]);
  }
}
```

**app.component.ts**
```
import { Component, OnInit } from '@angular/core';
import { QuillEditorComponent } from 'ngx-quill/src/quill-editor.component';
import { CardQuillComponent } from './card-quill.component'


@Component({
  selector: 'app-root',
  templateUrl: './app.component.component.html',
  styleUrls: ['./app.component.component.css']
})
export class AppComponent extends CardQuillComponent {

  constructor() {
    super();
  }

  ngOnInit() {}

  setEditor(editor) {
    this.editorInstance = editor;
  }
}
```

**app.component.html**
`<quill-editor (onEditorCreated)="setEditor($event)" [modules]="modules"></quill-editor>`

Thank you!

**Comment by KillerCodeMonkey** [comment] 2018-07-05 20:39
Yeah but this is a little Bit ugly, because APP component is a little Bit
strange to inherit from another component, because it is something like a
wrapper. Thats the cause mentioned to let cardcomponent inherit from
quilledtor component. So You could Use Your cardcomponent like the
quilleditorcompoment, but only with the Additional functions and custom
tag-name. You could Use the ViewChild decorator to Get the component
instance in You app component and Call the functions directly

pedrollmatias <notifications@github.com> schrieb am Do., 5. Juli 2018,
22:35:

**Comment by pedrollmatias** [comment] 2018-07-05 21:11
Let me understand... The problem is just because the app.component inherit from card-quill.component? I did it just for simplification (that didn't work haha), because in my real scenario I have a folder structure similar to this:
```
-- app
   -- modules
      -- components
         -- card-component (which inherit from card-quill.component)
         ...
   -- shared
      -- quill
         -- card-quill.component
         ...
   -- app.component
```

**Comment by KillerCodeMonkey** [comment] 2018-07-06 05:49
Ah okay, now i can rest in peace. 😅

I close this issue, because it is solved 👍

**Closed by KillerCodeMonkey** 2018-07-06 05:49 UTC
