### ISSUE TITLE
Support for reactive forms (formControl)

### ISSUE THREAD

**Issue by vaags** [KillerCodeMonkey/ngx-quill#16] opened 2017-03-05 14:31 UTC
First of all, thanks for your work on this great plugin! It works nicely with template driven forms.

I would, however, also like to use it with reactive forms. Thus i need to use "formControl" instead of "ngModel".

It appears that this is not fully supported(?)

My specific problem is that I am not able to use the "patchValue" method (of FormGroup) to insert content into the quill editor. The editor window remains empty after patching.

Entering new content by hand, and saving it, works fine however.

Please correct me if I'm mistaken.

Thanks!

**Comment by KillerCodeMonkey** [comment] 2017-03-05 17:20
Hey there --> there is an example repo for this project with some demo editors.

i added a reactive form with a "patchValue" button. it works there.
[ngx-quill-example demo](https://github.com/KillerCodeMonkey/ngx-quill-example) and the [source code](https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts)

Please close the issue if you could solve it. Or give some further information like your source code or an example like a plunkr.

**Comment by vaags** [comment] 2017-03-05 17:39
Thanks for your quick reply!

After looking at your code I realized my mistake. I had placed the patchValue method in ngOnInit(), but it needed to be in ngAfterViewInit(). Once I moved it there, everything works :)

Thanks again!

**Comment by mkaufm** [comment] 2017-04-05 13:49
But the initial value 'test' is not shown.
Shouldn't there be 'test' as the initial value when building the form like this:
```
this.form = fb.group({
      editor: ['test', Validators.required]
    });
```

**Comment by KillerCodeMonkey** [comment] 2017-04-05 18:38
should be fixed in v1.2.0 + added custom required attribute for required validation

**Closed by KillerCodeMonkey** 2017-04-05 18:38 UTC

**Comment by eltiare** [comment] 2019-07-09 16:23
@KillerCodeMonkey the example link is borked.

**Comment by KillerCodeMonkey** [comment] 2019-07-09 16:38
Because the issue is 2 years old. Just Checkout the links in the readme

Jeremy Nicoll <notifications@github.com> schrieb am Di., 9. Juli 2019,
18:23:
